/**
 * 
 */
package org.eclipsescout.contacts.shared.premium.ui.forms;

import javax.annotation.Generated;

import org.eclipse.scout.commons.annotations.Extends;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;
import org.eclipsescout.contacts.shared.ContactFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Extends(ContactFormData.class)
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ContactFormTabExtensionData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public ContactFormTabExtensionData() {
  }

  public Events getEvents() {
    return getFieldByClass(Events.class);
  }

  public static class Events extends AbstractTableFieldBeanData {

    private static final long serialVersionUID = 1L;

    public Events() {
    }

    @Override
    public AbstractTableRowData createRow() {
      return new AbstractTableRowData() {
        private static final long serialVersionUID = 1L;
      };
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return AbstractTableRowData.class;
    }
  }
}